import os
path=str(input("Enter the location of the directory where you want to download the songs: "))
print("Installing......")
file=open("location.txt","x")
file.write(path)
file.close()
os.system("pip install -r requirements.txt >/dev/null 2>&1")
os.system("chmod +x update.sh")
os.system("chmod +x uninstall.sh")
print("Done!")
